name: desafio_dev_mobile_sti3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  get: ^4.6.6
  hive: ^2.0.4
  dartz: ^0.10.1
  path_provider: ^2.0.2
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  fl_chart: ^0.69.0
  connectivity_plus: ^2.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0
  flutter_native_splash: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#014955"
  image: assets/app/splash.png
  android: true
  ios: true